# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 00:41
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometarefa', models.CharField(db_column='nomeTarefa', max_length=50)),
                ('responsavel', models.CharField(max_length=50)),
                ('datahora', models.DateTimeField(blank=True, db_column='dataHora', null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=9)),
                ('cor', models.CharField(max_length=30)),
                ('nummicrochip', models.CharField(blank=True, db_column='numMicrochip', max_length=15, null=True, unique=True)),
                ('especie', models.CharField(max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('datanasc', models.CharField(blank=True, db_column='dataNasc', max_length=10, null=True)),
                ('raca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descdiagnostico', models.CharField(max_length=300)),
                ('datadiagnostico', models.CharField(db_column='dataDiagnostico', max_length=10)),
                ('prescricao', models.CharField(blank=True, max_length=300, null=True)),
                ('diagnostico', models.CharField(max_length=20)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Historicodedoencas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedoenca', models.CharField(db_column='nomeDoenca', max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.CharField(max_length=10)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=18)),
                ('datafimhospedagem', models.CharField(db_column='dataFimHospedagem', max_length=10)),
                ('datainiciohospedagem', models.CharField(db_column='dataInicioHospedagem', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('valordiaria', models.DecimalField(db_column='valorDiaria', decimal_places=2, max_digits=5)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('nomeprocedimento', models.CharField(blank=True, db_column='nomeProcedimento', max_length=50, null=True)),
                ('data', models.CharField(blank=True, max_length=10, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavelprocedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprocedimento', models.ForeignKey(db_column='idProcedimento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telefoneproprietario',
            fields=[
                ('telefone', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('datanasc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Data nascimento')),
                ('cpf', models.IntegerField(unique=True, verbose_name='CPF')),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='Admin', max_length=5, verbose_name='Tipo de usuário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('apelido', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='animal',
            name='idstatus',
            field=models.ForeignKey(blank=True, db_column='idStatus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Status'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='nomeanimal',
            field=models.ForeignKey(blank=True, db_column='nomeAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Animal'),
        ),
        migrations.AddField(
            model_name='telefoneproprietario',
            name='idproprietario',
            field=models.ForeignKey(db_column='idProprietario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Proprietario'),
        ),
        migrations.AddField(
            model_name='responsavelprocedimento',
            name='idfuncionario',
            field=models.ForeignKey(db_column='idFuncionario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Funcionario'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='idfuncionario',
            field=models.ForeignKey(blank=True, db_column='idFuncionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Funcionario'),
        ),
        migrations.AddField(
            model_name='animal',
            name='idproprietario',
            field=models.ForeignKey(blank=True, db_column='idProprietario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Proprietario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idfuncionario',
            field=models.ForeignKey(blank=True, db_column='idFuncionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Funcionario'),
        ),
        migrations.AlterUniqueTogether(
            name='telefoneproprietario',
            unique_together=set([('telefone', 'idproprietario')]),
        ),
        migrations.AlterUniqueTogether(
            name='responsavelprocedimento',
            unique_together=set([('idprocedimento', 'idfuncionario')]),
        ),
    ]
